export default {
	cn:{
		index1:"汽车",
		index2:"零件",
		index3:"徽章",
		index4:"车胚币",
		index5:"列表",
		index6:"合成",
		index7:"等级",
		index8:"立即合成",
		index9:"请选择要合成的零件",
		index10:"父系",
		index11:"出售中",
		comp1:"发动机",
		comp2:"轮胎",
		comp3:"方向盘",
		comp4:"能量箱",
		comp5:"轮胎效率",
		car1:"石油车",
		car2:"电能车",
		car3:"氢能车",
		car4:"核能车",
		index12:"类型",
		index13:"稀有度",
		index14:"发动机加成",
		index15:"等级",
		index16:"类型和等级必须一致",
		index17:"零件数量不足",
		none:"暂无数据",
		active1:"激活码",
		active2:"立即激活",
		active3:"返回登录",
		active4:"激活",
		active5:"发送验证码",
		active6:"请输入激活码",
		breed1:"繁殖费用",
		use:"可用",
		zy:"去转移",
		ok:"确认",
		breed2:"繁殖",
		breed3:"不足",
		breed4:"请选择繁殖车辆",
		carDetail1:"编号",
		carDetail2:"速度",
		carDetail3:"汽车等级",
		carDetail4:"耐力效率",
		carDetail5:"繁殖次数",
		carDetail6:"动力值",
		carDetail7:"能量值",
		carDetail8:"耐力值",
		carDetail9:"方向值",
		carDetai20:"父系车辆详情",
		carDetai21:"子系车辆详情",
		carDetai22:"出售中",
		detail1:'赠送',
		detail2:'出售',
		detail3:'升级',
		detail4:'修复',
		detail5:'繁殖',
		detail6:'汽车详情',
		buy:"购买",
		give1:"用户邮箱",
		enter:"请输入",
		give2:"请输入邮箱",
		give3:"邮箱格式有误",
		login1:"邮箱账号",
		address:"地址",
		pledge:"质押金额",
		login2:"登录密码",
		login3:"登录",
		login4:"验证码登录",
		login5:"验证码",
		login6:"注册",
		login7:"密码登录",
		login8:"请勿频繁点击",
		login9:"请输入验证码",
		login10:"请输入密码",
		login11:"邀请码",
		login12:"确认登录密码",
		login13:"两次密码不一致",
		repair1:"修复费用",
		repair2:"余额不足",
		sell1:"请输入价格",
		sell2:"价格有误",
		sell3:"出售价格",
		sell4:"撤销出售",
		upgrade1:"升级费用",
		upgrade2:"驾驶时间(分)",
		loading1:'正在努力更新',
		loading2:'没有更多数据',
		loading3:'釋放立即刷新...',
		loading4:'下拉即可刷新...',
		loading5:'加载中...',
		low:'低到高',
		hight:"高到低",
		price:'价格',
		all:'全部',
		
		ban:"提示",
		ban2:"选择繁殖车辆",
		ban3:"升级提示",
		ban4:"车胚币详情",
		ban5:"新车详情",
		ban6:"汽车详情",
		ban7:"选择零件",
		ban8:"即将升级",
		ban9:"已完成修复",
		ban10:"您已将",
		ban11:"投入市场",
		ban12:"价格为",
		ban13:"赠送到",
		ban14:"已完成繁殖，获得车胚币",
		ban15:"合成成功率",
		ban16:"恭喜合成成功",
		ban17:"很遗憾，合成失败",
		ban18:"轮胎加成",
		ban19:"星级",
		ban20:"升级费用",
		ban21:"售卖",
		ban22:"打开",
		ban23:"取消售卖",
		ban24:"您需要取消出售吗",
		ban25:"我再想想",
		ban26:"购买费用",
		ban27:"加成",
		unfold:'筛选',
		unfold2:'收起',
		unfold3:'插槽属性',
		unfold4:'确认升级',
		unfold5:'立即驾驶',
		unfold6:'敬请期待',
		unfold7:'是否确认驾驶',
		balance:"余额:",
		max:"最大",
		type:"产品",
		pledge_:"质押",
	},
	en:{
		pledge_:"Stake",
		type:"Product",
		max:"Max",
		balance:"Balance:",
		address:"Address",
		pledge:"Pledge amount",
		index1:"Car",
		index2:"Parts",
		index3:"Badge",
		index4:"Embryo",
		index5:"List",
		index6:"Compound",
		index7:"Level",
		index8:"Compound",
		index9:"Please select parts",
		index10:"Father",
		index11:"On sale",
		comp1:"Engine",
		comp2:"Tyre",
		comp3:"Steering",
		comp4:"Energy",
		comp5:"tyre",
		car1:"Petroleum",
		car2:"Electric",
		car3:"Hydrogen",
		car4:"Nuclear",
		index12:"Type",
		index13:"Rarity",
		index14:"Addition",
		index15:"Level",
		index16:"The type and level must be consistent",
		index17:"inadequate",
		none:"no data",
		active1:"Activation code",
		active2:"Activation",
		active3:"Back",
		active4:"Activation",
		active5:"Send",
		active6:"Please enter the activation code",
		breed1:"cost",
		use:"available",
		zy:"transfer",
		ok:"Confirm",
		breed2:"breeding",
		breed3:"insufficient",
		breed4:"Please select",
		carDetail1:"number",
		carDetail2:"speed",
		carDetail3:"Level",
		carDetail4:"Efficiency",
		carDetail5:"breeding number",
		carDetail6:"power",
		carDetail7:"energy",
		carDetail8:"endurance",
		carDetail9:"direction",
		carDetai20:"patriarchal",
		carDetai21:"child",
		carDetai22:"sale",
		detail1:'Giving',
		detail2:'Sell',
		detail3:'Upgrade',
		detail4:'Repair',
		detail5:'Breeding',
		detail6:'Detail',
		buy:"Buy",
		give1:"Email",
		enter:"Please enter",
		give2:"Email",
		give3:"Incorrect email format",
		login1:"E-mail account",
		login2:"Password",
		login3:"Login",
		login4:"Code login",
		login5:"Verification code",
		login6:"Register",
		login7:"Password to login",
		login8:"Do not click frequently",
		login9:"Please enter the verification code",
		login10:"Please enter your password",
		login11:"Code",
		login12:"Confirm Password",
		login13:"Inconsistent passwords",
		repair1:"Cost of repair",
		repair2:"Lack of balance",
		sell1:"Please enter price",
		sell2:"The price is wrong",
		sell3:"Sale price",
		sell4:"Repeal",
		upgrade1:"Upgrade cost",
		upgrade2:"Drive Time (minutes)",
		loading1:'Being updated',
		loading2:'There is no data',
		loading3:'Release Refresh now...',
		loading4:'Drop down to refresh...',
		loading5:'In the load...',
		low:'Low to high',
		hight:"High to low",
		price:'Price',
		all:'All',
		
		ban:"Tips",
		ban2:"Choose",
		ban3:"Upgrade prompt",
		ban4:"Details",
		ban5:"New details",
		ban6:"The car details",
		ban7:"Choose",
		ban8:"Have to upgrade",
		ban9:"Have to repair",
		ban10:"You",
		ban11:"On the market",
		ban12:"The price for",
		ban13:"Give to the",
		ban14:"Finished breeding",
		ban15:"The success rate",
		ban16:"Synthesis of success",
		ban17:"Synthesis of failure",
		ban18:"Bonus to tire",
		ban19:"Level",
		ban20:"Upgrade cost",
		ban21:"Sell",
		ban22:"Open",
		ban23:"Cancel the sale",
		ban24:"Do you need to cancel the sale",
		ban25:"I think again",
		ban26:"Purchase cost",
		ban27:"add",
		unfold:'Filter',
		unfold2:'Close',
		unfold3:'Slot',
		unfold4:'Confirm',
		unfold5:'Drive',
		unfold6:'Coming soon ',
		unfold7:'Confirm to drive',
	}
}