//语言
const lang = {
	ch: {
		'pwdneed6':'密码必须为6位数字组成',
		'ddd':'是否确认驾驶',
		"reget":"重新获取",
		"drive0": "编号",
		"drive1": "类型",
		"drive2": "稀有度",
		"drive3": "汽车等级",
		"drive4": "轮胎效率",
		"drive5": "速度",
		"drive6": "能量",
		"drive7": "动力值",
		"drive8": "能量值",
		"drive9": "驾驶",
		"drive10": "能量不足",
		"drive11": "没有数据",
		"drive12": "编号",
		"drive13": "类型",
		"drive14": "稀有度",
		"drive15": "汽车等级",
		"drive16": "轮胎效率",
		"drive17": "速度",
		"drive18": "能量",
		"drive19": "动力值",
		"drive20": "能量值",
		"drive21": "驾驶",
		"drive22": "正在更新",
		"drive24": "裁剪",
		"drive25": "开始更新",
		"drive26": "更新接口请求出错",
		"drive27": "隐藏菜单",
		"drive28": "更新失败",
		"drive29": "更新失败",
		"drive30": "更新失败",
		"userCenter0": "个人中心",
		"userCenter1": "行驶次数",
		"userCenter2": "行驶时间",
		"userCenter3": "分钟",
		"userCenter4": "行驶里程",
		"userCenter5": "我的钱包",
		"userCenter6": "激活码",
		"userCenter7": "消费记录",
		"userCenter8": "路程记录",
		"userCenter9": "语言切换",
		"userCenter10": "信用",
		"userCenter11": "当前版本",
		"userCenter12": "区块链",
		"userCenter13": "退出账号",
		"userCenter14": "语言切换",
		"userCenter15": "中文",
		"userCenter16": "英文",
		"userCenter17": "确定",
		"userCenter18": "退出账号",
		"userCenter19": "确认退出当前账号吗",
		"userCenter20": "取消",
		"userCenter21": "确定",
		"map1": "启用当前位置",
		"map2": "地图样式",
		"map3": "缩放比例",
		"map4": "最小缩放",
		"map5": "最大缩放",
		"map6": "角度",
		"map7": "正北为",
		"map8": "斜度",
		"map9": "中心点",
		"driveStart0": "驾驶中",
		"driveStart1": "等待驾驶",
		"driveStart2": "平均时速",
		"driveStart3": "当前时速",
		"driveStart4": "总路程",
		"driveStart5": "运行时间",
		"driveStart6": "收益",
		"driveStart7": "能量剩余",
		"driveStart8": "下一个神秘盒子",
		"driveStart9": "轮胎效率",
		"driveStart10": "提示",
		"driveStart11": "恭喜您获得隐藏盲盒",
		"driveStart12": "立即打开",
		"driveStart13": "盲盒详情",
		"driveStart14": "发动机",
		"driveStart15": "轮胎",
		"driveStart16": "方向盘",
		"driveStart17": "能量箱",
		"driveStart18": "发动机加成",
		"driveStart19": "轮胎加成",
		"driveStart20": "方向盘加成",
		"driveStart21": "能量箱加成",
		"driveStart22": "星级",
		"driveStart23": "立即收下",
		"driveStart25": "能量已耗尽",
		"driveStart26": "出错了",
		"driveStart27": "请先结束驾驶",
		"driveStart28": "平均速度为",
		"driveStart29": "行驶数据无效",
		"driveStart30": "行驶已结束",
		"driveStart31": "能量已耗尽",
		"driveStart32": "能量已耗尽",
		"driveStart33": "裁剪",
		"map31": "启用当前位置",
		"map32": "地图样式",
		"map33": "缩放比例",
		"map34": "最小缩放",
		"map35": "最大缩放",
		"map36": "角度",
		"map37": "正北为",
		"map38": "斜度",
		"map39": "中心点",
		"map20": "当前时速",
		"map21": "总路程",
		"map22": "运行时间",
		"map23": "等待驾驶",
		"map24": "驾驶中",
		"map26": "启用当前位置",
		"map27": "缩放比例",
		"map28": "最小缩放",
		"map29": "最大缩放",
		"map210": "角度",
		"map211": "正北为",
		"map212": "斜度",
		"activation0": "激活码",
		"activation1": "激活码",
		"activation2": "可用",
		"activation3": "总数",
		"activation4": "复制",
		"activation5": "已使用",
		"activation7": "准备复制的数据",
		"activation8": "已复制到剪切板",
		"consumption0": "消费记录",
		"consumption1": "收到车辆",
		"consumption2": "赠送车辆",
		"consumption4": "组件的",
		"consumption5": "值",
		"consumption6": "表示当前活动的",
		"consumption7": "选项",
		"consumption8": "组件的",
		"consumption9": "值",
		"consumption10": "表示当前那个",
		"consumption11": "是活动的",
		"consumption12": "赠",
		"consumption13": "收",
		"consumption14": "购",
		"consumption15": "售",
		"consumption16": "升级",
		"consumption17": "修复",
		"consumption18": "繁殖",
		"consumption19": "赠",
		"consumption20": "收",
		"consumption21": "由于",
		"consumption22": "的内部机制问题",
		"consumption23": "快速切换",
		"consumption24": "不会触发",
		"consumption25": "的连续变化",
		"consumption26": "需要在结束时重置状态",
		"consumption27": "滑动结束",
		"consumption28": "分别设置",
		"consumption29": "和",
		"consumption30": "的状态",
		"consumption31": "更新当前对应",
		"consumption32": "的数据",
		"consumption33": "注意这里请用",
		"consumption34": "而非",
		"consumption35": "因为需要触发列表渲染",
		"myWallet0": "我的钱包",
		"myWallet1": "货币转移",
		"myWallet2": "充值",
		"myWallet3": "提币",
		"myWallet4": "兑换",
		"myWallet5": "转移",
		"myWallet6": "创建钱包",
		"myWallet7": "重绑钱包",
		"myWallet9": "消费钱包",
		"myWallet10": "链上钱包",
		"myWallet11": "错误",
		"myWallet12": "错误",
		"myWallet13": "错误",
		"myWallet14": "连接钱包中",
		"myWallet15": "请稍后",
		"roadDetail0": "路程记录",
		"roadDetail1": "类型",
		"roadDetail2": "运行时间",
		"roadDetail3": "总路程",
		"roadDetail4": "平均时速",
		"roadDetail5": "分享",
		"roadDetail7": "当前页",
		"roadDetail8": "将",
		"roadDetail9": "内容绘制到",
		"roadDetail10": "对象中",
		"roadDetail11": "截屏绘制图片成功",
		"roadDetail12": "保存图片成功",
		"roadDetail13": "销毁",
		"roadDetail14": "图片",
		"roadDetail15": "已保存至相册",
		"roadDetail16": "保存失败",
		"roadDetail17": "保存图片失败",
		"roadDetail18": "保存失败",
		"roadDetail19": "截屏绘制图片失败",
		"roadRecord0": "路程记录",
		"roadRecord1": "编号",
		"roadRecord2": "类型",
		"roadRecord3": "结束日期",
		"roadRecord5": "作为返回值返回",
		"editPwd0": "密码修改",
		"editPwd1": "验证码",
		"editPwd2": "获取",
		"editPwd3": "设置新密码",
		"editPwd4": "保存",
		"editPwd6": "请填写",
		"editPwd7": "请填写正确的",
		"editPwd8": "地址",
		"editPwd9": "触发器可以同时用",
		"editPwd10": "和",
		"editPwd11": "请填写验证码",
		"editPwd12": "请填写新密码",
		"editPwd13": "请填写正确的",
		"editPwd14": "验证码已发送",
		"editPwd15": "验证码发送失败",
		"editPwd16": "倒计时结束后再发送",
		"editPwd17": "保存成功",
		"editPwd18": "保存失败",
		"userEdit0": "信息编辑",
		"userEdit1": "昵称",
		"userEdit2": "性别",
		"userEdit3": "密码修改",
		"userEdit4": "未设置",
		"userEdit5": "性别设置",
		"userEdit6": "男",
		"userEdit7": "女",
		"userEdit8": "秘密",
		"userEdit9": "确定",
		"userEdit10": "头像选择",
		"userEdit11": "确定",
		"userEdit12": "昵称修改",
		"userEdit13": "确定",
		"userEdit15": "删除图片",
		"userEdit16": "新增图片",
		"userEdit17": "当设置",
		"userEdit18": "为",
		"userEdit19": "时",
		"userEdit20": "为数组格式",
		"userEdit21": "否则为对象格式",
		"userEdit22": "昵称最多",
		"userEdit23": "个字符",
		"exchange0": "操作中",
		"exchange1": "货币转移",
		"exchange2": "从",
		"exchange3": "消费钱包",
		"exchange4": "链上钱包",
		"exchange5": "到",
		"exchange6": "链上钱包",
		"exchange7": "消费钱包",
		"exchange8": "交易币种",
		"exchange9": "交易数量",
		"exchange10": "全部",
		"exchange11": "可用",
		"exchange12": "确认",
		"exchange14": "请填写交易数量",
		"exchange15": "消费钱包",
		"exchange16": "转到",
		"exchange17": "链上钱包",
		"exchange18": "链上钱包",
		"exchange19": "转到",
		"exchange20": "操作中",
		"exchange21": "兑换",
		"exchange22": "从",
		"charge0": "充值",
		"charge1": "选择币种",
		"charge2": "扫码进行充值",
		"charge3": "复制地址",
		"charge5": "复制成功",
		"exchange23": "到",
		"exchange24": "交易数量",
		"exchange25": "全部",
		"exchange26": "可用",
		"exchange27": "获得数量",
		"exchange28": "确认",
		"exchange210": "请填写交易数量",
		"exchange211": "如果为负数",
		"exchange212": "转成正数处理",
		"exchange213": "先去掉",
		"exchange214": "号",
		"exchange215": "并保存",
		"exchange216": "幂数大于小数点后面的数字位数时",
		"exchange217": "后面加",
		"exchange218": "幂数大于等于",
		"exchange219": "小数点的",
		"exchange220": "位置",
		"exchange221": "前面加",
		"exchange222": "提交成功",
		"registerWallet0": "注册链上钱包",
		"registerWallet1": "助记词由英文单词组成",
		"registerWallet2": "请抄写并妥善保管",
		"registerWallet3": "助记词丢失",
		"registerWallet4": "无法找回",
		"registerWallet5": "请务必备份好",
		"registerWallet6": "请勿截屏分享或电子设备储存",
		"registerWallet7": "这可能遭到第三方恶意采集",
		"registerWallet8": "造成资产损失",
		"registerWallet9": "我已保存",
		"registerWalletInput0": "注册链上钱包",
		"registerWalletInput1": "请确认您的助记词",
		"registerWalletInput2": "来完成注册脸上钱包",
		"registerWalletInput3": "确认",
		"registerWalletInput5": "创建成功",
		"reStartWallet0": "重绑钱包",
		"reStartWallet1": "钱包密码",
		"reStartWallet2": "邮箱验证码",
		"reStartWallet3": "获取",
		"reStartWallet4": "导入新钱包助记词",
		"reStartWallet5": "请输入助记词",
		"reStartWallet6": "单词用空格隔开",
		"reStartWallet7": "提交",
		"reStartWallet9": "请填写",
		"reStartWallet10": "请填写邮箱验证码",
		"reStartWallet11": "请设置钱包密码",
		"reStartWallet12": "自定义规则判断是否包含字母",
		"reStartWallet13": "钱包密码必须为纯数字",
		"reStartWallet14": "请填写助记词",
		"reStartWallet15": "助记词请用空格分隔",
		"reStartWallet16": "不可包含特殊符号",
		"reStartWallet17": "请填写正确的",
		"reStartWallet18": "验证码已发送",
		"reStartWallet19": "倒计时结束后再发送",
		"seeKeyCode0": "备份助记词",
		"seeKeyCode1": "助记词由英文单词组成",
		"seeKeyCode2": "请抄写并妥善保管",
		"seeKeyCode3": "助记词丢失",
		"seeKeyCode4": "无法找回",
		"seeKeyCode5": "请务必备份好",
		"seeKeyCode6": "请勿截屏分享或电子设备储存",
		"seeKeyCode7": "这可能遭到第三方恶意采集",
		"seeKeyCode8": "造成资产损失",
		"seeKeyCode9": "按住可显示",
		"setNewPwd20": "创建钱包密码",
		"setNewPwd21": "确认密码",
		"setNewPwd23": "两次密码不一致",
		"setNewPwd24": "指定每一行的宽度",
		"setNewPwd25": "每个宽度中间用空格隔开",
		"setNewPwd26": "指定每一列的宽度",
		"setNewPwd27": "每个宽度中间用空格隔开",
		"setNewPwd0": "创建钱包密码",
		"setNewPwd1": "输入密码",
		"setNewPwd3": "指定每一行的宽度",
		"setNewPwd4": "每个宽度中间用空格隔开",
		"setNewPwd5": "指定每一列的宽度",
		"setNewPwd6": "每个宽度中间用空格隔开",
		"setWalletPwd20": "钱包密码修改",
		"setWalletPwd21": "确认新密码",
		"setWalletPwd23": "两次密码不一致",
		"setWalletPwd24": "指定每一行的宽度",
		"setWalletPwd25": "每个宽度中间用空格隔开",
		"setWalletPwd26": "指定每一列的宽度",
		"setWalletPwd27": "每个宽度中间用空格隔开",
		"setWalletPwd0": "钱包密码修改",
		"setWalletPwd1": "输入新密码",
		"setWalletPwd3": "指定每一行的宽度",
		"setWalletPwd4": "每个宽度中间用空格隔开",
		"setWalletPwd5": "指定每一列的宽度",
		"setWalletPwd6": "每个宽度中间用空格隔开",
		"walletPwd0": "钱包密码",
		"walletPwd1": "忘记密码",
		"walletPwd3": "密码错误",
		"walletPwd4": "指定每一行的宽度",
		"walletPwd5": "每个宽度中间用空格隔开",
		"walletPwd6": "指定每一列的宽度",
		"walletPwd7": "每个宽度中间用空格隔开",
		"walletRecord0": "记录",
		"walletRecord1": "总额",
		"walletRecord2": "提币",
		"walletSetting0": "钱包设置",
		"walletSetting1": "备份助记词",
		"walletSetting2": "修改钱包密码",
		"walletSetting3": "重绑钱包",
		"withdrawal0": "操作中",
		"withdrawal1": "提币",
		"withdrawal2": "选择币种",
		"withdrawal3": "交易地址",
		"withdrawal4": "交易数量",
		"withdrawal5": "全部",
		"withdrawal6": "可用",
		"withdrawal7": "确认",
		"withdrawal9": "请填写交易地址",
		"withdrawal10": "请填写交易数量",
		"withdrawal11": "提交成功",
		"withdrawal12": "扫码出错"
	},
	en: {
		'pwdneed6':'Password must be 6 digits',
		'ddd':'Confirm driving',
		"reget":"Reacquire",
		"drive0": "number",
		"drive1": "type",
		"drive2": "rarity",
		"drive3": "car grade",
		"drive4": "tire efficiency",
		"drive5": "speed",
		"drive6": "energy",
		"drive7": "power value",
		"drive8": "energy value",
		"drive9": "driving",
		"drive10": "Insufficient energy",
		"drive11": "No data",
		"drive12": "number",
		"drive13": "type",
		"drive14": "rarity",
		"drive15": "car grade",
		"drive16": "tire efficiency",
		"drive17": "speed",
		"drive18": "energy",
		"drive19": "power value",
		"drive20": "energy value",
		"drive21": "driving",
		"drive22": "updating",
		"drive24": "crop",
		"drive25": "Start updating",
		"drive26": "Error in updating interface request",
		"drive27": "Hide menu",
		"drive28": "update failed",
		"drive29": "update failed",
		"drive30": "update failed",
		"userCenter0": "personal center",
		"userCenter1": "times of driving",
		"userCenter2": "driving time",
		"userCenter3": "minutes",
		"userCenter4": "mileage",
		"userCenter5": "my wallet",
		"userCenter6": "activation code",
		"userCenter7": "consumption record",
		"userCenter8": "journey record",
		"userCenter9": "language switch",
		"userCenter10": "credit",
		"userCenter11": "current version",
		"userCenter12": "Blockchain",
		"userCenter13": "log out",
		"userCenter14": "language switch",
		"userCenter15": "Chinese",
		"userCenter16": "English",
		"userCenter17": "ok",
		"userCenter18": "Exit the account",
		"userCenter19": "Are you sure you want to exit the current account",
		"userCenter20": "cancel",
		"userCenter21": "ok",
		"map1": "Enable the current location",
		"map2": "map style",
		"map3": "zoom ratio",
		"map4": "minimum zoom",
		"map5": "Maximum zoom",
		"map6": "angle",
		"map7": "due north is",
		"map8": "slope",
		"map9": "center point",
		"driveStart0": "driving",
		"driveStart1": "waiting for driving",
		"driveStart2": "average speed",
		"driveStart3": "current speed",
		"driveStart4": "total distance",
		"driveStart5": "running time",
		"driveStart6": " revenue",
		"driveStart7": "energy surplus",
		"driveStart8": "mystical Box",
		"driveStart9": "tire efficiency",
		"driveStart10": "hint",
		"driveStart11": "Congratulations on getting the hidden blind box",
		"driveStart12": "open now",
		"driveStart13": "blind box details",
		"driveStart14": "engine",
		"driveStart15": "tires",
		"driveStart16": "steering wheel",
		"driveStart17": "energy box",
		"driveStart18": "engine bonus",
		"driveStart19": "tire bonus",
		"driveStart20": "steering wheel bonus",
		"driveStart21": "energy box bonus",
		"driveStart22": "star rating",
		"driveStart23": "accept it now",
		"driveStart25": "the energy has been exhausted",
		"driveStart26": "Error",
		"driveStart27": "please finish driving first",
		"driveStart28": "the average speed is",
		"driveStart29": "invalid driving data",
		"driveStart30": "the driving is over",
		"driveStart31": "the energy has been exhausted",
		"driveStart32": "the energy has been exhausted",
		"driveStart33": "crop",
		"map31": "Enable the current location",
		"map32": "map style",
		"map33": "zoom ratio",
		"map34": "minimum zoom",
		"map35": "maximum zoom",
		"map36": "angle",
		"map37": "due north is",
		"map38": "slope",
		"map39": "center point",
		"map20": "Current speed",
		"map21": "total distance",
		"map22": "running time",
		"map23": "Waiting for driving",
		"map24": "driving",
		"map26": "Enable the current location",
		"map27": "zoom ratio",
		"map28": "minimum zoom",
		"map29": "Maximum zoom",
		"map210": "angle",
		"map211": "due north is",
		"map212": "slope",
		"activation0": "activation code",
		"activation1": "activation code",
		"activation2": "available",
		"activation3": "total number",
		"activation4": "copy",
		"activation5": "already used",
		"activation7": "data to be replicated",
		"activation8": "copied to the clipboard",
		"consumption0": "consumption record",
		"consumption1": "vehicle received",
		"consumption2": "complimentary vehicle",
		"consumption4": "of the component",
		"consumption5": "value",
		"consumption6": "indicates the current activity",
		"consumption7": "options",
		"consumption8": "of the component",
		"consumption9": "value",
		"consumption10": "indicates the current one",
		"consumption11": "it is active",
		"consumption12": "gift",
		"consumption13": "received",
		"consumption14": "purchase",
		"consumption15": "for sale",
		"consumption16": "upgrade",
		"consumption17": "repair",
		"consumption18": "reproduction",
		"consumption19": "gift",
		"consumption20": "received",
		"consumption21": "due to",
		"consumption22": "internal mechanism of",
		"consumption23": "quick switching",
		"consumption24": "will not trigger",
		"consumption25": "continuous change of",
		"consumption26": "The status needs to be reset at the end",
		"consumption27": "end of sliding",
		"consumption28": "set separately",
		"consumption29": "and",
		"consumption30": "status",
		"consumption31": "Update the current correspondence",
		"consumption32": "data",
		"consumption33": "Please use it here",
		"consumption34": "instead of",
		"consumption35": "Because the list rendering needs to be triggered",
		"myWallet0": "my wallet",
		"myWallet1": "Transfer",
		"myWallet2": "Deposit",
		"myWallet3": "withdraw",
		"myWallet4": "exchange",
		"myWallet5": "transfer",
		"myWallet6": "Create a wallet",
		"myWallet7": "Reset wallet",
		"myWallet9": "consumer wallet",
		"myWallet10": "chain wallet",
		"myWallet11": "Error",
		"myWallet12": "Error",
		"myWallet13": "Error",
		"myWallet14": "connected in wallet",
		"myWallet15": "please wait",
		"roadDetail0": "journey record",
		"roadDetail1": "type",
		"roadDetail2": "running time",
		"roadDetail3": "total distance",
		"roadDetail4": "average speed",
		"roadDetail5": "share",
		"roadDetail7": "current page",
		"roadDetail8": "will",
		"roadDetail9": "the content is drawn to",
		"roadDetail10": "in the object",
		"roadDetail11": "Screen capture and picture drawing succeeded",
		"roadDetail12": "Save the picture successfully",
		"roadDetail13": "destroy",
		"roadDetail14": "picture",
		"roadDetail15": "saved to album",
		"roadDetail16": "save failed",
		"roadDetail17": "Failed to save the picture",
		"roadDetail18": "save failed",
		"roadDetail19": "Screen capture failed to draw pictures",
		"roadRecord0": "Journey record",
		"roadRecord1": "number",
		"roadRecord2": "type",
		"roadRecord3": "end date",
		"roadRecord5": "returned as a return value",
		"editPwd0": "password modification",
		"editPwd1": "verification code",
		"editPwd2": "get",
		"editPwd3": "Set a new password",
		"editPwd4": "save",
		"editPwd6": "please fill in",
		"editPwd7": "Please fill in the correct form",
		"editPwd8": "address",
		"editPwd9": "Triggers can be used at the same time",
		"editPwd10": "and",
		"editPwd11": "Please fill in the verification code",
		"editPwd12": "Please fill in the new password",
		"editPwd13": "Please fill in the correct form",
		"editPwd14": "verification code has been sent",
		"editPwd15": "Failed to send verification code",
		"editPwd16": "Send it after the countdown",
		"editPwd17": "Save successfully",
		"editPwd18": "Save failed",
		"userEdit0": "information editing",
		"userEdit1": "nickname",
		"userEdit2": "gender",
		"userEdit3": "password modification",
		"userEdit4": "not set",
		"userEdit5": "gender setting",
		"userEdit6": "male",
		"userEdit7": "female",
		"userEdit8": "secret",
		"userEdit9": "OK",
		"userEdit10": "avatar selection",
		"userEdit11": "OK",
		"userEdit12": "nickname modification",
		"userEdit13": "OK",
		"userEdit15": "Delete pictures",
		"userEdit16": "Add a picture",
		"userEdit17": "when setting",
		"userEdit18": "is",
		"userEdit19": "when",
		"userEdit20": "in array format",
		"userEdit21": "Otherwise, it is in object format",
		"userEdit22": "Most nicknames",
		"userEdit23": "characters",
		"exchange0": "in operation",
		"exchange1": "transfer",
		"exchange2": "from",
		"exchange3": "consumer wallet",
		"exchange4": "chain wallet",
		"exchange5": "to",
		"exchange6": "chain wallet",
		"exchange7": "Consumer wallet",
		"exchange8": "transaction currency",
		"exchange9": "number of transactions",
		"exchange10": "all",
		"exchange11": "available",
		"exchange12": "confirm",
		"exchange14": "Please fill in the transaction quantity",
		"exchange15": "Consumer wallet",
		"exchange16": "Go to",
		"exchange17": "chain wallet",
		"exchange18": "chain wallet",
		"exchange19": "Go to",
		"exchange20": "in operation",
		"exchange21": "exchange",
		"exchange22": "from",
		"charge0": "recharge",
		"charge1": "Select currency",
		"charge2": "scan code to recharge",
		"charge3": "copy address",
		"charge5": "Copy succeeded",
		"exchange23": "to",
		"exchange24": "number of transactions",
		"exchange25": "all",
		"exchange26": "available",
		"exchange27": "acquired quantity",
		"exchange28": "Confirm",
		"exchange210": "Please fill in the transaction quantity",
		"exchange211": "If it is negative",
		"exchange212": "Convert to positive number",
		"exchange213": "Remove it first",
		"exchange214": "No.",
		"exchange215": "and save",
		"exchange216": "When the power number is greater than the number of digits after the decimal point",
		"exchange217": "add after ",
		"exchange218": "Power is greater than or equal to",
		"exchange219": "decimal point",
		"exchange220": "location",
		"exchange221": "add before ",
		"exchange222": "Submitted successfully",
		"registerWallet0": "register chain wallet",
		"registerWallet1": "mnemonics consist of English words",
		"registerWallet2": "Please copy and keep it properly",
		"registerWallet3": "mnemonic is lost",
		"registerWallet4": "cannot be retrieved",
		"registerWallet5": "Please make sure to make a good backup",
		"registerWallet6": "Do not take screenshots to share or store in electronic devices",
		"registerWallet7": "This may be maliciously collected by a third party",
		"registerWallet8": "causing asset loss",
		"registerWallet9": "I have saved",
		"registerWalletInput0": "Register chain wallet",
		"registerWalletInput1": "Please confirm your mnemonic",
		"registerWalletInput2": "To complete the registration of wallet on your face",
		"registerWalletInput3": "confirm",
		"registerWalletInput5": "Successfully created",
		"reStartWallet0": "Reset wallet",
		"reStartWallet1": "reset password",
		"reStartWallet2": "mailbox verification code",
		"reStartWallet3": "get",
		"reStartWallet4": "import mnemonics",
		"reStartWallet5": "Please enter a mnemonic",
		"reStartWallet6": "Words are separated by spaces",
		"reStartWallet7": "submit",
		"reStartWallet9": "please fill in",
		"reStartWallet10": "Please fill in the email verification code",
		"reStartWallet11": "please set the wallet password",
		"reStartWallet12": "User-defined rules to determine whether letters are included",
		"reStartWallet13": "wallet password must be pure numbers",
		"reStartWallet14": "Please fill in the mnemonic",
		"reStartWallet15": "please separate mnemonics with spaces",
		"reStartWallet16": "cannot contain special symbols",
		"reStartWallet17": "Please fill in the correct form",
		"reStartWallet18": "verification code has been sent",
		"reStartWallet19": "send it after the countdown",
		"seeKeyCode0": "backup mnemonic",
		"seeKeyCode1": "mnemonics consist of English words",
		"seeKeyCode2": "Please copy and keep it properly",
		"seeKeyCode3": "mnemonic is missing",
		"seeKeyCode4": "cannot be retrieved",
		"seeKeyCode5": "Please make a good backup",
		"seeKeyCode6": "Do not share screen shots or store them in electronic devices",
		"seeKeyCode7": "This may be maliciously collected by a third party",
		"seeKeyCode8": "causing asset losses",
		"seeKeyCode9": "press and hold to display",
		"setNewPwd20": "Create wallet password",
		"setNewPwd21": "Confirm password",
		"setNewPwd23": "Two passwords are inconsistent",
		"setNewPwd24": "Specify the width of each line",
		"setNewPwd25": "The middle of each width is separated by a space",
		"setNewPwd26": "Specify the width of each column",
		"setNewPwd27": "The middle of each width is separated by a space",
		"setNewPwd0": "Create wallet password",
		"setNewPwd1": "Enter password",
		"setNewPwd3": "Specify the width of each line",
		"setNewPwd4": "The middle of each width is separated by a space",
		"setNewPwd5": "Specify the width of each column",
		"setNewPwd6": "The middle of each width is separated by a space",
		"setWalletPwd20": "wallet password modification",
		"setWalletPwd21": "Confirm the new password",
		"setWalletPwd23": "Two passwords are inconsistent",
		"setWalletPwd24": "Specify the width of each line",
		"setWalletPwd25": "The middle of each width is separated by a space",
		"setWalletPwd26": "Specify the width of each column",
		"setWalletPwd27": "The middle of each width is separated by a space",
		"setWalletPwd0": "wallet password modification",
		"setWalletPwd1": "Enter a new password",
		"setWalletPwd3": "Specify the width of each line",
		"setWalletPwd4": "Each width is separated by a space in the middle",
		"setWalletPwd5": "Specify the width of each column",
		"setWalletPwd6": "Each width is separated by a space in the middle",
		"walletPwd0": "wallet password",
		"walletPwd1": "Forgot password",
		"walletPwd3": "wrong password",
		"walletPwd4": "Specify the width of each line",
		"walletPwd5": "The middle of each width is separated by a space",
		"walletPwd6": "Specify the width of each column",
		"walletPwd7": "The middle of each width is separated by a space",
		"walletRecord0": "Record",
		"walletRecord1": "Total amount",
		"walletRecord2": "Withdraw",
		"walletSetting0": "wallet setting",
		"walletSetting1": "backup mnemonic",
		"walletSetting2": "change wallet password",
		"walletSetting3": "Reset wallet",
		"withdrawal0": "in operation",
		"withdrawal1": "withdraw",
		"withdrawal2": "select currency",
		"withdrawal3": "transaction address",
		"withdrawal4": "transaction quantity",
		"withdrawal5": "all",
		"withdrawal6": "available",
		"withdrawal7": "confirm",
		"withdrawal9": "Please fill in the transaction address",
		"withdrawal10": "Please fill in the transaction quantity",
		"withdrawal11": "Submitted successfully",
		"withdrawal12": "Error in scanning code"
	}
}
export default {
	lang
}
